**0. Import des bibliothèques**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**1. Import du dataset**

In [3]:
df = pd.read_csv('crime_incidents_messy.csv')
df.head()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,...,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,...,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,...,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,...,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN

**3. Audit de la qualité des données**

In [4]:
# Dimensions du dataset
df.shape

(5250, 33)

In [5]:
# Types de données
df.dtypes

incident_id            object
crime_type             object
district               object
city                   object
state                  object
address                object
latitude              float64
longitude             float64
incident_datetime      object
officer_id             object
officer_first_name     object
officer_last_name      object
badge_number          float64
suspect_id             object
suspect_first_name     object
suspect_last_name      object
suspect_age           float64
suspect_gender         object
suspect_race           object
victim_id              object
victim_first_name      object
victim_last_name       object
victim_age            float64
victim_gender          object
victim_phone           object
weapon_used            object
severity               object
case_status            object
resolution             object
num_arrests           float64
property_loss_usd      object
reported_online        object
notes                  object
dtype: object

In [6]:
# Valeurs manquantes
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100).round(2)

pd.DataFrame({
    "Valeurs manquantes": missing,
    "Pourcentage": missing_pct
}).query("`Valeurs manquantes` > 0")

                    Valeurs manquantes  Pourcentage
latitude                           258         4.91
longitude                          289         5.50
incident_datetime                  340         6.48
badge_number                       312         5.94
suspect_id                         810        15.43
suspect_first_name                 810        15.43
suspect_last_name                  810        15.43
suspect_age                       1097        20.90
suspect_gender                    1413        26.91
suspect_race                      1601        30.50
victim_id                          257         4.90
victim_first_name                  257         4.90
victim_last_name                   257         4.90
victim_age                         562        10.70
victim_gender                     1000        19.05
victim_phone                      1056        20.11
weapon_used                        970        18.48
severity                           355         6.76
case_status                        731        13.92
resolution                         951        18.11
num_arrests                        333         6.34
property_loss_usd                  436         8.30
reported_online                    504         9.60
notes                             1069        20.36

In [7]:
# Doublons
df.duplicated().sum()

np.int64(200)

In [8]:
# Statistiques descriptives
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
incident_id,5250,5050,INC002079,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crime_type,5250,182,Fire Setting,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
district,5250,131,Nor,273,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,5250,8,Riverside,740,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,5250,10,FL,554,NaN,NaN,NaN,NaN,NaN,NaN,NaN
address,5250,4895,3089 Elm Blvd,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,4992.0,NaN,NaN,NaN,40.778811,23.243225,25.00242,30.966472,36.967123,43.051502,199.9842
longitude,4961.0,NaN,NaN,NaN,-88.60761,37.214207,-121.975849,-108.040512,-94.65644,-80.588056,99.7873
incident_datetime,4910,4675,2018-01-30 20:00:44,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
officer_id,5250,150,OFF0015,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
officer_first_name,5250,128,Jessica,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
officer_last_name,5250,30,Anderson,199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
badge_number,4938.0,NaN,NaN,NaN,5558.581612,2591.581049,1002.0,3316.25,5567.0,7862.0,9999.0
suspect_id,4440,798,SUS00130,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
suspect_first_name,4440,30,David,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
suspect_last_name,4440,30,Brown,164,NaN,NaN,NaN,NaN,NaN,NaN,NaN
suspect_age,4153.0,NaN,NaN,NaN,48.418493,43.504819,-75.0,29.0,46.0,62.0,298.0
suspect_gender,3837,12,F,361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
suspect_race,3649,10,Black,397,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_id,4993,987,VIC00620,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_first_name,4993,30,Mary,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_last_name,4993,30,Wright,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_age,4688.0,NaN,NaN,NaN,52.349403,48.104315,-90.0,27.75,49.0,71.0,298.0
victim_gender,4250,12,Male,394,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_phone,4194,3994,477-604-3892,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weapon_used,4280,13,Hands/Feet,368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
severity,4895,14,4,376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
case_status,4519,12,closed,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolution,4299,9,Arrest Made,504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_arrests,4917.0,NaN,NaN,NaN,2.262152,1.994556,-5.0,1.0,2.0,4.0,5.0
property_loss_usd,4814,4592,20611.06,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reported_online,4746,10,0,539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notes,4181,3915,Incident at 3089 Elm Blvd. Officer responded a...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Valeurs et fréquences de chaque colonne

for colonne in df.columns:
    display(
        df[colonne]
        .value_counts(dropna=False)
        .rename_axis(colonne)
        .reset_index(name="Nombre")
    )

     incident_id  Nombre
0      INC002079       2
1      INC002731       2
2      INC000067       2
3      INC002436       2
4      INC000912       2
...          ...     ...
5045   INC003247       1
5046   INC000314       1
5047   INC002761       1
5048   INC001022       1
5049   INC003981       1

[5050 rows x 2 columns]

            crime_type  Nombre
0         Fire Setting      84
1                   DV      82
2                ARSON      80
3         Drug Offence      79
4            Deception      79
..                 ...     ...
177      Sex Assault         1
178  assault & battery       1
179       CYBER  CRIME       1
180              dui         1
181    theft/larceny         1

[182 rows x 2 columns]

           district  Nombre
0               Nor     273
1               Sou     265
2         SOUTHWEST     106
3             South     102
4             NORTH     101
..              ...     ...
126     Southeast         1
127        West           1
128     southeast         1
129             mid       1
130     northeast         1

[131 rows x 2 columns]

          city  Nombre
0    Riverside     740
1  Centerville     691
2     Lakewood     664
3  Springfield     656
4      Oakdale     634
5    Maplewood     622
6     Fairview     622
7    Hillcrest     621

  state  Nombre
0    FL     554
1    AZ     549
2    TX     538
3    NY     536
4    IL     535
5    PA     526
6    NC     513
7    GA     503
8    CA     501
9    OH     495

               address  Nombre
0        3089 Elm Blvd       3
1      8303 Lincoln St       3
2         9657 Park Rd       3
3        4806 Elm Blvd       3
4        1587 River Rd       3
...                ...     ...
4890   892 Sunset Blvd       1
4891     4434 Elm Blvd       1
4892  1065 Sunset Blvd       1
4893  6419 Sunset Blvd       1
4894   9379 Lincoln St       1

[4895 rows x 2 columns]

       latitude  Nombre
0           NaN     258
1     33.207301       3
2     44.365032       3
3     38.760757       3
4     30.832196       2
...         ...     ...
4746  42.576022       1
4747  38.941858       1
4748  41.627732       1
4749  28.903176       1
4750  29.914376       1

[4751 rows x 2 columns]

       longitude  Nombre
0            NaN     289
1    -106.402030       3
2     -99.836125       3
3     -86.670091       3
4     -84.017884       2
...          ...     ...
4722 -107.652152       1
4723 -119.174353       1
4724  -84.509472       1
4725 -120.334201       1
4726  -85.522020       1

[4727 rows x 2 columns]

        incident_datetime  Nombre
0                     NaN     340
1     2021-01-18 03:05:30       3
2     2018-01-30 20:00:44       3
3     2024-05-03 06:55:57       3
4     2022-08-25 07:18:44       2
...                   ...     ...
4671  2021-12-18 17:27:18       1
4672  2023-06-23 04:09:19       1
4673  2018-04-25 14:38:24       1
4674  2023-03-29 09:54:50       1
4675  2018-08-26 04:50:54       1

[4676 rows x 2 columns]

    officer_id  Nombre
0      OFF0015      53
1      OFF0008      52
2      OFF0069      52
3      OFF0135      50
4      OFF0131      48
..         ...     ...
145    OFF0032      23
146    OFF0013      21
147    OFF0025      19
148    OFF0051      19
149    OFF0049      15

[150 rows x 2 columns]

    officer_first_name  Nombre
0              Jessica     198
1                James     183
2                Donna     173
3              Michael     172
4                Sarah     172
..                 ...     ...
123            KAREN         1
124            EMILY         1
125           THOMAS         1
126             JOHN         1
127            MICHAEL       1

[128 rows x 2 columns]

   officer_last_name  Nombre
0           Anderson     199
1              Jones     196
2              Green     191
3              Brown     186
4              Allen     185
5                Lee     185
6            Jackson     184
7              Scott     184
8             Miller     183
9              Moore     180
10            Garcia     180
11            Nguyen     180
12            Walker     180
13            Martin     177
14             Young     176
15             Davis     176
16             White     175
17            Wright     174
18            Torres     173
19           Johnson     173
20             Smith     171
21              Hall     168
22          Williams     168
23            Thomas     164
24              Hill     161
25          Thompson     160
26            Flores     160
27            Wilson     157
28            Taylor     152
29            Harris     152

      badge_number  Nombre
0              NaN     312
1           5137.0       6
2           8685.0       5
3           3532.0       5
4           6231.0       5
...            ...     ...
3627        1469.0       1
3628        9072.0       1
3629        9450.0       1
3630        7567.0       1
3631        9532.0       1

[3632 rows x 2 columns]

    suspect_id  Nombre
0          NaN     810
1     SUS00130      15
2     SUS00524      14
3     SUS00427      13
4     SUS00014      13
..         ...     ...
794   SUS00071       1
795   SUS00257       1
796   SUS00720       1
797   SUS00719       1
798   SUS00583       1

[799 rows x 2 columns]

   suspect_first_name  Nombre
0                 NaN     810
1               David     176
2             Barbara     171
3             Michael     165
4             Charles     161
5               James     160
6            Jennifer     158
7               Donna     156
8              Ashley     155
9             Jessica     153
10            Richard     153
11            Matthew     150
12              Nancy     148
13              Karen     148
14            William     148
15             Robert     146
16              Sarah     145
17              Linda     144
18              Susan     144
19           Patricia     144
20               John     144
21             Thomas     143
22            Anthony     140
23               Mark     140
24             Daniel     139
25              Emily     139
26           Michelle     139
27               Mary     136
28             Joseph     133
29              Carol     132
30              Chris     130

   suspect_last_name  Nombre
0                NaN     810
1              Brown     164
2             Harris     163
3              Scott     161
4             Wright     161
5              Green     161
6             Miller     157
7                Lee     155
8           Williams     154
9              Jones     154
10             Moore     153
11              Hall     153
12           Jackson     151
13            Torres     151
14            Martin     150
15              Hill     149
16            Thomas     149
17             Smith     149
18           Johnson     148
19            Walker     148
20             Allen     148
21             White     147
22            Flores     147
23            Wilson     147
24          Thompson     142
25            Garcia     140
26             Davis     140
27          Anderson     130
28            Taylor     130
29            Nguyen     126
30             Young     112

     suspect_age  Nombre
0            NaN    1097
1           19.0      82
2           36.0      82
3           46.0      80
4           26.0      76
..           ...     ...
214        161.0       1
215        283.0       1
216        -42.0       1
217        265.0       1
218        259.0       1

[219 rows x 2 columns]

   suspect_gender  Nombre
0             NaN    1413
1               F     361
2          female     347
3            male     326
4         Unknown     323
5               f     323
6               M     317
7           Other     315
8            MALE     311
9          Female     309
10         FEMALE     305
11              m     301
12           Male     299

   suspect_race  Nombre
0           NaN    1601
1         Black     397
2      Hispanic     383
3         BLACK     383
4         asian     369
5       Unknown     367
6         White     365
7      hispanic     362
8         white     347
9         Other     339
10        Asian     337

    victim_id  Nombre
0         NaN     257
1    VIC00620      13
2    VIC00498      12
3    VIC00641      12
4    VIC00014      12
..        ...     ...
983  VIC00894       1
984  VIC00555       1
985  VIC00157       1
986  VIC00818       1
987  VIC00991       1

[988 rows x 2 columns]

   victim_first_name  Nombre
0                NaN     257
1               Mary     203
2              Emily     202
3            Jessica     183
4              James     183
5              Donna     182
6               John     177
7              Chris     173
8           Michelle     170
9              Nancy     168
10            Joseph     168
11          Patricia     168
12           Richard     167
13           Barbara     166
14            Robert     166
15             David     165
16             Carol     165
17           Michael     164
18           William     163
19            Daniel     163
20           Matthew     161
21           Charles     161
22              Mark     160
23             Karen     158
24           Anthony     158
25            Ashley     155
26            Thomas     154
27             Linda     153
28          Jennifer     147
29             Susan     146
30             Sarah     144

   victim_last_name  Nombre
0               NaN     257
1            Wright     192
2            Torres     189
3               Lee     187
4             Jones     184
5            Nguyen     179
6            Martin     179
7              Hill     179
8            Flores     177
9            Harris     173
10         Anderson     172
11           Miller     172
12            White     171
13            Young     171
14           Garcia     169
15           Wilson     168
16         Thompson     167
17            Brown     166
18            Scott     166
19            Moore     164
20            Green     162
21         Williams     161
22           Thomas     158
23             Hall     157
24            Davis     157
25           Taylor     153
26            Smith     151
27           Walker     148
28          Jackson     143
29          Johnson     140
30            Allen     138

     victim_age  Nombre
0           NaN     562
1          21.0      73
2          67.0      70
3          12.0      70
4          15.0      69
..          ...     ...
256       165.0       1
257       183.0       1
258       234.0       1
259       -39.0       1
260       150.0       1

[261 rows x 2 columns]

   victim_gender  Nombre
0            NaN    1000
1           Male     394
2        Unknown     383
3              M     376
4         female     363
5          Other     360
6              m     360
7           MALE     349
8           male     345
9              f     342
10        FEMALE     329
11        Female     326
12             F     323

          victim_phone  Nombre
0                  NaN    1056
1         477-604-3892       3
2         648-499-1968       3
3         632-522-8864       2
4     (926) -54-0-5868       2
...                ...     ...
3990        6223265920       1
3991      214-897-2917       1
3992      855-624-8658       1
3993      639-378-9582       1
3994      277-861-5193       1

[3995 rows x 2 columns]

     weapon_used  Nombre
0            NaN     970
1     Hands/Feet     368
2        Unarmed     361
3          Rifle     346
4          Knife     339
5          KNIFE     335
6   Blunt Object     334
7   blunt object     327
8            Gun     318
9          hands     317
10       Firearm     316
11        Pistol     310
12       firearm     306
13           Bat     303

    severity  Nombre
0          4     376
1     MEDIUM     368
2       high     366
3        low     366
4          1     363
5        NaN     355
6        Med     355
7          3     348
8        Low     347
9     Medium     347
10  CRITICAL     346
11      Crit     337
12         2     331
13  Critical     325
14      High     320

            case_status  Nombre
0                   NaN     731
1                closed     399
2              Resolved     389
3   Under Investigation     387
4                  Open     381
5                  open     380
6          Investgation     377
7                Closed     374
8                  OPEN     371
9                Pendng     370
10               CLOSED     368
11              Pending     367
12  under investigation     356

       resolution  Nombre
0             NaN     951
1     Arrest Made     504
2     arrest made     491
3       No Arrest     490
4         warning     490
5       Dismissed     480
6  Warning Issued     479
7      Arres Made     476
8  Case Dismissed     455
9       NO ARREST     434

    num_arrests  Nombre
0           0.0     848
1           3.0     790
2           4.0     786
3           2.0     775
4           5.0     767
5           1.0     767
6           NaN     333
7          -1.0      42
8          -5.0      37
9          -4.0      37
10         -2.0      36
11         -3.0      32

     property_loss_usd  Nombre
0                  NaN     436
1              4865.21       3
2             20611.06       3
3             26845.31       2
4             15963.38       2
...                ...     ...
4588          44417.98       1
4589          16330.48       1
4590          13138.25       1
4591          43851.12       1
4592           40572.1       1

[4593 rows x 2 columns]

   reported_online  Nombre
0                0     539
1              NaN     504
2               No     491
3                1     484
4            False     483
5              yes     473
6              Yes     473
7             True     458
8              YES     453
9               no     453
10              NO     439

                                                  notes  Nombre
0                                                   NaN    1069
1     Incident at 3089 Elm Blvd. Officer responded a...       3
2     Incident at 310 Elm Blvd. Officer responded at...       3
3     Incident at 5409 River Rd. Officer responded a...       3
4     Incident at 1587 River Rd. Officer responded a...       3
...                                                 ...     ...
3911  Incident at 7349 Park Rd. Officer responded at...       1
3912  Incident at 3221 Cedar Lane. Officer responded...       1
3913  Incident at 6637 Lincoln St. Officer responded...       1
3914  Incident at 3781 Sunset Blvd. Officer responde...       1
3915  Incident at 4334 Main St. Officer responded at...       1

[3916 rows x 2 columns]

In [ ]:
# Statistiques descriptives pour les colonnes numériques
df.select_dtypes(include="number").describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,4992.0,40.778811,23.243225,25.002420,30.966472,36.967123,43.051502,199.9842
longitude,4961.0,-88.607610,37.214207,-121.975849,-108.040512,-94.656440,-80.588056,99.7873
badge_number,4938.0,5558.581612,2591.581049,1002.000000,3316.250000,5567.000000,7862.000000,9999.0000
suspect_age,4153.0,48.418493,43.504819,-75.000000,29.000000,46.000000,62.000000,298.0000
victim_age,4688.0,52.349403,48.104315,-90.000000,27.750000,49.000000,71.000000,298.0000
num_arrests,4917.0,2.262152,1.994556,-5.000000,1.000000,2.000000,4.000000,5.0000